name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '00 16 * * *' # 8:00 AM UTC+4  
    - cron: '00 04 * * *' # 8:00 PM UTC+4 
    #- cron: '00 06 * * 1-5' -> Runs five days mon to fri
jobs:
     run_postman_tests:
       runs-on: ubuntu-latest
       steps:
        - name: Checkout the code
          uses: actions/checkout@v6.1.0
          
        - name: Setup Node.js environment
          uses: actions/setup-node@v6.5.0
          with: 
            node-version: '24'

        - name: Install newman and htmlextra globally
          run: |
               npm install -g newman 
               npm install -g newman-reporter-htmlextra
        - name: Run the Potsman Collection with Newman
          run: |
              newman run 'InWarrenty-flow collection QA.postman_collection.json' \
              -e 'QA.postman_environment.json' \
              -d 'testdata.csv' \
              -r cli,htmlextra \
              --reporter-htmlextra-export ./newman/index.html
        - name: Upload a Build Artifact
          if: always()
          uses: actions/upload-artifact@v7.0.1
          with:
             name: Newman Report
             path: newman/*.html
             
        - name: Creating github page branch
          if: always()
           # You may pin to the exact commit or the version.
           # uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
          uses: peaceiris/actions-gh-pages@v4.1.0
          with: 
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: newman/

        - name: Send email notifications
          if: always() 
          uses: dawidd6/action-send-mail@v18
          with:
   
              server_address: smtp.gmail.com
              server_port: 465
              username: ${{ secrets.EMAIL_USERNAME }}
              password: ${{ secrets.EMAIL_PASSWORD }}
              subject: Phoenix In-Warrenty Flow Test Execution Notification
              to: abhilashagadgil2026@gmail.com
              from: Abhilasha from Github Actions <${{ secrets.EMAIL_USERNAME }}>
              body: |
                    Hello,
          
                    Phoenix inwarrenty flow tests has been executed. The report has been published and the
                    Link to live report is: https://abhilashag24.github.io/Phoenix-In-Warranty-Flow/

                    Regards,
        
